FROM ghcr.io/astral-sh/uv:0.5.5-python3.12-alpine

RUN apk update && \
    apk upgrade && \
    apk add --no-cache ffmpeg && \
    apk add make bash

COPY . .

RUN uv pip install --system -r pyproject.toml --extra bot

CMD [ "python3", "-u", "bot" ]
