FROM python:3.9

RUN apt update && \
    apt upgrade -y && \
    apt install curl -y

COPY . .

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

RUN /root/.cargo/bin/uv pip install --system -r inference_server/requirements.txt

CMD [ "python3", "-u", "inference_server" ]
