---
name: Basic on-PR checks

on:
  pull_request:
    branches:
    - master

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python3
      uses: actions/setup-python@v3

    - name: Setup uv
      uses: yezz123/setup-uv@v4
      with:
        uv-venv: venv

    - name: Install dependencies
      run: |
        uv pip install -r pyproject.toml
        uv pip install -e .

    - name: Run pre-commit
      run: |
        pre-commit run --all-files

    - name: Run tests
      run: |
        uv pip install -r pyproject.toml --extra asr-service
        pytest -v tests/
